forward-primer: GTGCCAGCMGCCGCGGTAA
reverse-primer: GGACTACHVGGGTWTCTAAT
forward-primer-raw: CTTTCCCTACACGACGCTCTTCCGATCTGTGCCAGCMGCCGCGGTAA
reverse-primer-raw: GGAGTTCAGACGTGTGCTCTTCCGATCTGGACTACHVGGGTWTCTAAT
